Numerous changes/additions to deployment scripts and configuration
 * fedora script now works properly
 * there is literally one tomcat startup script now
   * many changes to this script: classpath, status, etc.
 * better status reporting
 * updated configuration to match changes to [1291]
 * Add topaz log4j configuration into /etc


git-svn-id: http://svn.topazproject.org/svn/head@1343 48088309-b40f-0410-b149-b14953253675

diff --git a/deploy/src/tomcat b/deploy/src/tomcat
--- a/deploy/src/tomcat
+++ b/deploy/src/tomcat
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# $HeadURL::                                                                  $
+# $HeadURL::                                                                                      $
 # $Id$
 #
 # Tomcat init script
@@ -9,11 +9,7 @@
 # Licensed under the Educational Community License version 1.0
 # http://opensource.org/licenses/ecl1.php
 
-# chkconfig: 345 92 12
-# description: topaz fedora server
-
 # What to customize/do:
-# - chkconfig and description lines above
 # - Define defaults and/or overrides (minimum is <basename>_CATALINA_HOME)
 # - Ensure the jsvc binary is somewhere
 
@@ -28,7 +24,7 @@
 # Defaults:
 CATALINA_HOME=
 USER="topaz"
-JAVA_HOME="/home/tools/java"
+JAVA_HOME="/usr/local/topaz/java"
 TOMCAT_OPTS="-Xmx256m"
 VARDIR="/var"
 LOGDIR="${VARDIR}/log/tomcat"
@@ -37,11 +33,23 @@ JSVC="jsvc"
 JVM="server"
 
 # Overrides: basename_CATALINA_HOME, basename_TOMCAT_OPTS, basename_USER
+SERVERS="ecqs mckoi mulgara fedora search topaz plosone"
 ecqs_CATALINA_HOME=/usr/local/topaz/esup-cas-quick-start-2.0.6-1/jakarta-tomcat-5.0.28
 ecqs_TOMCAT_OPTS="-Xmx256m"
 topaz_CATALINA_HOME=/usr/local/topaz/topaz-tomcat55
 search_CATALINA_HOME=/usr/local/topaz/search-tomcat55
 mulgara_CATALINA_HOME=/usr/local/topaz/mulgara-tomcat55
+plosone_CATALINA_HOME=/usr/local/topaz/plosone-tomcat55
+
+# These ports are only for printing status. If they're accurate, status will be better
+PORT=
+ecqs_PORT=7443
+topaz_PORT=8000
+search_PORT=9092
+mulgara_PORT=9091
+plosone_PORT=8080
+fedora_PORT=9090
+mckoi_PORT=9157
 
 #
 # Should not need to modify stuff below here
@@ -68,11 +76,13 @@ expand () { eval "$1=\${${BASENAME}_$1:-\$$1}"; }
 expand CATALINA_HOME
 expand TOMCAT_OPTS
 expand USER
+expand PORT
 
 # Having CATALINA_HOME set properly is critical
-export CATALINA_HOME
-[ -z "$CATALINA_HOME" ] && log "Must set/define CATALINA_HOME (for $BASENAME)" && exit 1
-[ \! -d "$CATALINA_HOME" ] && log "CATALINA_HOME ($CATALINA_HOME) does not exist" && exit 1
+check_catalina() {
+  [ -z "$CATALINA_HOME" ] && log "Must set/define CATALINA_HOME (for $BASENAME)" && exit 1
+  [ \! -d "$CATALINA_HOME" ] && log "CATALINA_HOME ($CATALINA_HOME) does not exist" && exit 1
+}
 
 # Setup other catalina defaults
 CATALINA_ENDORSED_DIRS=${CATALINA_HOME}/common/endorsed
@@ -81,27 +91,40 @@ CATALINA_POLICY=${CATALINA_HOME}/conf/catalina.policy
 # Compute classpath
 getjars () { echo `(cd /; find $1 -name '*.jar')` | tr ' ' ':'; }
 TC=${CATALINA_HOME}
-CLASSPATH=`getjars ${TC}/bin`:`getjars ${TC}/server/lib`:`getjars ${TC}/common`
+CLASSPATH="$TC/bin/bootstrap.jar:$TC/bin/commons-logging-api.jar"
+# Add /etc/topaz/container/<basename>/lib/*.jar OR /etc/topaz/container/common/lib/*.jar
+if [ -d /etc/topaz/container/$BASENAME/lib ]; then
+  EXTRA_CLASSES=`getjars /etc/topaz/container/$BASENAME/lib`
+elif [ -d /etc/topaz/container/common/lib ]; then
+  EXTRA_CLASSES=`getjars /etc/topaz/container/common/lib`
+fi
+[ -n "$EXTRA_CLASSES" ] && CLASSPATH=$EXTRA_CLASSES:$CLASSPATH
+# Add /etc/topaz/container/<basename>/classes OR /etc/topaz/container/common/classes
+CLASS_OVERRIDES=common
+[ -d /etc/topaz/container/$BASENAME/classes ] && CLASS_OVERRIDES=$BASENAME
+CLASSPATH=/etc/topaz/container/$CLASS_OVERRIDES/classes:$CLASSPATH
+# Add the javac compiler
+CLASSPATH="$JAVA_HOME/lib/tools.jar:$CLASSPATH"
 
 # Define options for JSVC
 JSVC_OPTS="-outfile ${STDLOG} -errfile ${ERRLOG} -pidfile ${PIDFILE} -cp ${CLASSPATH}"
 [ -n "$JVM" ] && JSVC_OPTS="${JSVC_OPTS} -jvm ${JVM}"
 [ -n "$USER" ] && JSVC_OPTS="$JSVC_OPTS -user ${USER}"
-JSVC_OPTS="${JSVC_OPTS}
+JSVC_OPTS="${JSVC_OPTS} \
   -Djava.endorsed.dirs=${CATALINA_ENDORSED_DIRS} \
   -Dcatalina.base=${CATALINA_HOME} \
-  -Dcatalina.home=${CATALINA_HOME} \
-  -Djava.security.manager \
-  -Djava.security.policy=${CATALINA_POLICY}"
+  -Dcatalina.home=${CATALINA_HOME}"
+#  -Djava.security.manager \
+#  -Djava.security.policy=${CATALINA_POLICY}
 JSVC_OPTS="${JSVC_OPTS} ${TOMCAT_OPTS}"
 
 # Find jsvc (in case root's PATH) doesn't contain it
 if which ${JSVC} >/dev/null 2>&1; then
   # For some reason, jsvc has trouble starting if it is not an absolute path
   JSVC=`which ${JSVC}`
-else
-  [ -x "${TC}/bin/jsvc" ]    && JSVC="${TC}/bin/jsvc"    && log "Using ${JSVC}"
-  [ -x /usr/local/bin/jsvc ] && JSVC=/usr/local/bin/jsvc && log "Using ${JSVC}"
+elif [ -x "${TC}/bin/jsvc" ];          then JSVC="${TC}/bin/jsvc"
+elif [ -x /usr/local/topaz/bin/jsvc ]; then JSVC=/usr/local/topaz/bin/jsvc
+elif [ -x /usr/local/bin/jsvc ];       then JSVC=/usr/local/bin/jsvc
 fi
 
 # You must be root to run jsvc
@@ -111,6 +134,7 @@ test_root() { [ `id -u` -ne 0 ] && echo "You must be root!" && exit 1; }
 create_dirs() { mkdir -p ${LOGDIR} ${PIDDIR}; }
 
 jsvc() {
+  check_catalina
   # Make sure that we have jsvc
   if ! which ${JSVC} >/dev/null 2>&1; then
     echo "Cannot find ${JSVC} executable"
@@ -133,8 +157,26 @@ jsvc_start() {
   chmod ugo+r ${PIDFILE}
 }
 
+
 case "$1" in
   start)
+    # Don't try to start up twice!
+    if [ -e ${PIDFILE} ]; then
+      PID=`cat ${PIDFILE}`
+      if ps -p ${PID} >/dev/null; then
+        echo "${BASENAME} already running (${PID})"
+	exit 0
+      fi
+    fi
+    # jsvc doesn't abort if somebody else is on our port, so let's be smart!
+    if [ -n "$PORT" ]; then
+      TMPFILE=/tmp/${BASENAME}.status.$$
+      if lsof -i:$PORT -Fp > ${TMPFILE}; then
+        echo "No PID file for ${BASENAME}, but port $PORT already in use by pid `cat ${TMPFILE}`"
+	rm -f ${TMPFILE}
+	exit 1
+      fi
+    fi
     test_root
     create_dirs
     log "Starting ${BASENAME} in ${CATALINA_HOME}"
@@ -146,6 +188,11 @@ case "$1" in
     PID=`cat ${PIDFILE} 2>/dev/null`
     log "Stopping ${BASENAME} (${PID})"
     jsvc -stop
+    if [ -e ${PIDFILE} ]; then
+      echo "Unable to stop ${BASENAME} (${PID})"
+      kill -QUIT ${PID}
+      exit 1
+    fi
     ;;
   restart|reload)
     test_root
@@ -162,7 +209,7 @@ case "$1" in
       if ps o "pid user rss %mem etime time %cpu comm" -p ${PID} > ${TMPFILE} 2>&1; then
         echo "${BASENAME} (${PID}) is running from ${CATALINA_HOME}"
         cat ${TMPFILE}
-        lsof -n -i -a -p $PID
+        lsof -n -P -i -a -p $PID | grep "LISTEN"
       else
         echo "${BASENAME} not running"
       fi
@@ -170,6 +217,36 @@ case "$1" in
     else
       echo "${BASENAME} not running"
     fi
+    ;;
+  report)
+    # Spit out a very simple status dump (really used by reportall below)
+    # Note: fedora and mckoi will almost always report xxx(unknown)
+    if [ -e ${PIDFILE} ]; then
+      PID=`cat ${PIDFILE}`
+      if ps -p $PID >/dev/null; then
+        PORTS=`lsof -p $PID -a -iTCP -Fn -n -P | grep -v '-' | sort | uniq | tr 'n' ' '`
+        echo "$PID $BASENAME `echo $PORTS`"
+      else
+        echo "$BASENAME not running -- but PIDFILE ($PIDFILE:$PID) exists"
+      fi
+    elif [ -n "$PORT" ]; then
+      PID=`lsof -i:$PORT | grep LISTEN | awk '{print $2}'`
+      if [ -n "$PID" ]; then
+        PORTS=`lsof -p $PID -a -iTCP -Fn -n -P | grep -v '-' | sort | uniq | tr 'n' ' '`
+        echo "`echo $PID` unknown($BASENAME) `echo $PORTS`"
+      else
+        # No PIDFILE and noting listening on our configured PORT
+        echo "$BASENAME not running on port $PORT"
+      fi
+    else
+      # No PIDFILE and no configured PORT
+      echo "$BASENAME not running"
+    fi
+    ;;
+  reportall)
+    for server in ${SERVERS}; do
+      $0 --basename $server report
+    done
     ;;
   *)
     echo "Usage: $0 [--basename name] {start|stop|restart|status}"
