re #241 "Cleanup" tomcat script
Addresses most of the issues in #241:
 * Add better usage
 * Use SU_USER, SU_GROUP variables (per Ron's suggestion)
 * Allow scripts to be run as different users and do appropriate things
   without extraneous errors from things the scripts shouldn't have been
   attempting anyway
 * Don't try to find JAVA_HOME. It must be set before.
 * Add something to show the version
 * Try to verify the server is up and running before returning
 * Add a "dump" command to cause a thread dump

Still needed eventually:
 * Separate script for diagnostics like reportall and extended status
 * Stupid <basename>_ENV_VAR overrides -- but this will probably force
   separate diagnostics script. It will mean changes to some of the RPMs
   as well to ensure sysconfig stuff is setup properly. It is quite a bit
   more to test


git-svn-id: http://svn.topazproject.org/svn/head@2437 48088309-b40f-0410-b149-b14953253675

diff --git a/packages/tools/src/main/resources/bin/tomcat b/packages/tools/src/main/resources/bin/tomcat
--- a/packages/tools/src/main/resources/bin/tomcat
+++ b/packages/tools/src/main/resources/bin/tomcat
@@ -8,39 +8,53 @@
 #
 # Licensed under the Educational Community License version 1.0
 # http://opensource.org/licenses/ecl1.php
-
-# Environment:
-#  Variable      Default -- Description
-#  ------------- --------------------------------------------------------------
-#  TRUST_STORE   /etc/topaz/keystore.jks -- The value to set the
-#                javax.net.ssl.trustStore system property. Set to "default" to
-#                turn this off.
-#  TRUST_PASS    changeit -- The value for the javax.net.ssl.trustStorePassword
-#                system property. Set to "default" to turn this off.
-#  CATALINA_HOME This is where tomcat is installed. It is usually overridden
-#                by <basename>_CATALINA_HOME.
-#  JAVA_HOME     /usr/local/topaz/java -- This is where the JDK is installed.
-#                It really should be set before running this script.
-#  TOMCAT_OPTS   -Xmx400m -XX:MaxPermSize=256m -- These are the options to be
-#                used for starting tomcat. <basename>_TOMCAT_OPTS overrides
-#                these.
-#  STARTUP       jsvc -- This can be "jsvc" or "java". If set to jsvc and jsvc
-#                is not found, we revert ot running via java. If starting or
-#                stopping with jsvc, must be root
 #
 # TODO:
 # - Get rid of stopid <basename>_ENV_VAR override stuff (must do diags first)
 # - Move report/reportall diagnostics to a separate script
+# - Pause until startup is complete
+
+usage() { # Args: $BASENAME
+cat <<EOF; exit 1
+usage: $1 [options] start|stop|restart|status|report|dump
+
+Options:
+  -h, --help    Usage information (this message)
+  -b basename   The name of the program. i.e. cas, topaz, plosone
+  -n timeout    The number of seconds to wait after starting or stopping
+                (default=60)
+  -f            If we can't stop in <timeout>, send TERM signal
+  -F            If we can't stop in <timeout>, send KILL signal
+
+Environment:
+  Variable      Default -- Description
+  ------------- --------------------------------------------------------------
+  TRUST_STORE   /etc/topaz/keystore.jks -- The value to set the
+                javax.net.ssl.trustStore system property. Set to "default" to
+                turn this off.
+  TRUST_PASS    changeit -- The value for the javax.net.ssl.trustStorePassword
+                system property. Set to "default" to turn this off.
+  CATALINA_HOME This is where tomcat is installed. It is usually overridden
+                by <basename>_CATALINA_HOME.
+  JAVA_HOME     This is where the JDK is installed.
+  TOMCAT_OPTS   -Xmx400m -XX:MaxPermSize=256m -- These are the options to be
+                used for starting tomcat. <basename>_TOMCAT_OPTS overrides
+                these.
+  STARTUP       jsvc -- This can be "jsvc" or "java". If set to jsvc and jsvc
+                is not found, we revert ot running via java. If starting or
+                stopping with jsvc, must be root
+  SU_USER       The user to start/stop server as.
+EOF
+}
 
 # Defaults:
-USER="topaz"
-GROUP=$USER
+[ -z "$SU_USER" ] && SU_USER="topaz"
+SU_GROUP=$SU_USER
 TOPAZ_LOCAL="/usr/local/topaz"
 TOPAZ_CONFIG="/etc/topaz"
 [ -z "$TRUST_STORE" ] && TRUST_STORE=$TOPAZ_CONFIG/keystore.jks
 [ -z "$TRUST_PASS" ]  && TRUST_PASS=changeit
 [ -z "$CATALINA_HOME" ] && CATALINA_HOME=
-[ -z "$JAVA_HOME" ] && [ -d $TOPAZ_LOCAL/java ] && JAVA_HOME="$TOPAZ_LOCAL/java"
 [ -z "$TOMCAT_OPTS" ] && TOMCAT_OPTS="-Xmx400m -XX:MaxPermSize=256m"
 [ -z "$STARTUP" ] && STARTUP="jsvc"
 VARDIR="/var"
@@ -48,6 +62,7 @@ LOGDIR="${VARDIR}/log/topaz"
 PIDDIR="${VARDIR}/run/topaz"
 JSVC="jsvc"
 JVM="server"
+verbose=
 
 # Overrides: basename_CATALINA_HOME, basename_TOMCAT_OPTS, basename_USER
 SERVERS="cas mulgara fedora topaz plosone"
@@ -79,11 +94,13 @@ if [ "$OS" != "apple" -a ! -e "$JAVA_HOME/lib/tools.jar" ]; then
   echo "JAVA_HOME ($JAVA_HOME) is not JDK (no tools.jar)" && exit 1
 fi
 
+[ "--help" == "$1" ] && usage $BASENAME
+
 # Deprecated:
 [ "--basename" == "$1" ] && BASENAME=$2 && shift 2
 
 # Parse command line options
-while getopts b:n:fF opt; do
+while getopts b:n:fFhVv opt; do
   case $opt in
     b) # Change the basename (used mostly for testing)
        BASENAME="$OPTARG"
@@ -97,24 +114,50 @@ while getopts b:n:fF opt; do
     n) # Number of seconds to wait for processes to start or stop
        timeout="$OPTARG"
        ;;
+    h) # help: display usage
+       usage $BASENAME
+       ;;
+    V) # Show version
+       echo "Version: $Id$"
+       exit 1
+       ;;
+    v) # Turn on verbose
+       verbose=1
+       ;;
   esac
 done
 shift `expr $OPTIND - 1`
+[ $# -eq 0 ] && usage $BASENAME
 
 # Define log filename
 STDLOG="${LOGDIR}/${BASENAME}.out.`date +%Y-%m-%d`"
-touch ${STDLOG}
-[ `id -u` -eq 0 -a -n "$USER" ] && chown ${USER} $STDLOG
 STDLOG_LNK="${LOGDIR}/${BASENAME}.out"
-[ -h "${STDLOG_LNK}" ] && rm -f ${STDLOG_LNK}
-ln -s `basename ${STDLOG}` ${STDLOG_LNK}
+create_log() {
+  if [ `id -u` -eq 0 -a -n "$SU_USER" ] ; then
+    touch ${STDLOG}
+    [ -h "${STDLOG_LNK}" ] && rm -f ${STDLOG_LNK}
+    ln -s `basename ${STDLOG}` ${STDLOG_LNK}
+    chown $SU_USER $STDLOG
+    chown $SU_USER $STDLOG_LNK
+  else
+    STDLOG=$STDLOG_LNK
+    [ ! -e "$STDLOG" ] && echo "Unable to create $STDLOG. Should be root." && exit 1
+  fi
+}
 
 # Log stuff w/date as tomcat doesn't include dates when logging!
-log() { echo "`date` $*" >> $STDLOG; echo $*; }
+log() {
+  [ -w "$STDLOG" ] && echo "`date` $*" >> $STDLOG;
+  echo "$*";
+}
+debug() {
+  [ -w "$STDLOG" ] && echo "`date` $*" >> $STDLOG;
+  [ -n "$verbose" ] && echo "$*";
+}
 
 # Setup TOMCAT_TRUST_OPTS properly
 if [ -n "$TRUST_STORE" -a "$TRUST_STORE" != "default" ]; then
-  [ -n "$USER" -a -e "$TRUST_STORE" ] && chown $USER.$GROUP $TRUST_STORE
+  [ -n "$SU_USER" -a -e "$TRUST_STORE" -a `id -u` -eq 0 ] && chown $SU_USER:$SU_GROUP $TRUST_STORE
   TOMCAT_TRUST_OPTS="-Djavax.net.ssl.trustStore=${TRUST_STORE}"
   if [ -n "$TRUST_PASS" -a "$TRUST_PASS" != "default" ]; then
     TOMCAT_TRUST_OPTS="$TOMCAT_TRUST_OPTS -Djavax.net.ssl.trustStorePassword='$TRUST_PASS'"
@@ -125,7 +168,7 @@ fi
 expand () { eval "$1=\${${BASENAME}_$1:-\$$1}"; }
 expand CATALINA_HOME
 expand TOMCAT_OPTS
-expand USER
+expand SU_USER
 expand PORT
 
 # Having CATALINA_HOME set properly is critical
@@ -161,7 +204,7 @@ PIDFILE="${PIDDIR}/${BASENAME}-${STARTUP}.pid"
 # Define options for JSVC
 JSVC_OPTS="-outfile ${STDLOG} -pidfile ${PIDFILE} -cp ${CLASSPATH}"
 [ -n "$JVM" ] && JSVC_OPTS="${JSVC_OPTS} -jvm ${JVM}"
-[ -n "$USER" ] && JSVC_OPTS="$JSVC_OPTS -user ${USER}"
+[ -n "$SU_USER" ] && JSVC_OPTS="$JSVC_OPTS -user ${SU_USER}"
 JSVC_OPTS="${JSVC_OPTS} \
   -Djava.endorsed.dirs=${CATALINA_ENDORSED_DIRS} \
   -Dcatalina.base=${CATALINA_HOME} \
@@ -180,7 +223,7 @@ test_root() { [ `id -u` -ne 0 ] && echo "You must be root!" && exit 1; }
 # Create dirs
 create_dirs() {
   mkdir -p ${PIDDIR}
-  [ -n "$USER" ] && chown -R ${USER} ${PIDDIR}
+  [ -n "$SU_USER" -a `id -u` -eq 0 ] && chown -R ${SU_USER} ${PIDDIR}
 }
 
 # Catalina configuration
@@ -218,8 +261,11 @@ jsvc_stop() {
 }
 
 su_cmd() {
-  if [ -n "$USER" ]; then
-    su $USER -s /bin/bash -c "$* >>$STDLOG 2>&1 & echo \$! >$PIDFILE"
+  if [ -n "$SU_USER" -a `id -u` -eq 0 ] ; then
+    su $SU_USER -s /bin/bash -c "$* >>$STDLOG 2>&1 & echo \$! >$PIDFILE"
+  elif [ -n "$SU_USER" -a `id -u` -ne `id -u $SU_USER` ] ; then
+    echo "Must be root or $SU_USER to run \"""$@""\""
+    exit 1
   else
     "$@" >>$STDLOG 2>&1 &
     echo $! >$PIDFILE
@@ -228,11 +274,34 @@ su_cmd() {
 
 java_start() {
   su_cmd $JAVA_HOME/bin/java -$JVM $TOMCAT_OPTS $TOMCAT_TRUST_OPTS $CATALINA_OPTS start
-  # TODO: Wait here until PID in $PIDFILE is listening on $PORT (or until some timeout)
+  # Give it a few seconds to start (to create PID file)
+  PID=`cat ${PIDFILE} 2>/dev/null`
+  i=1
+  while [ -z "$PID" ] ; do
+    sleep 1
+    PID=`cat ${PIDFILE} 2>/dev/null`
+    i=$((i+1))
+    [ $i -gt "$timeout" ] && break
+  done
+  # Now see if we're listening yet
+  if [ -n "$PID" -a -n "$PORT" ]; then
+    RESULT=`$LSOF -i :$PORT | grep LISTEN`
+    while [ -z "$RESULT" ] ; do
+      sleep 1
+      RESULT=`$LSOF -i :$PORT | grep LISTEN`
+      i=$((i+1))
+      [ $i -gt "$timeout" ] && break
+    done
+  fi
+  PID=`cat ${PIDFILE} 2>/dev/null`
+  if [ -z "$PID" ]; then
+    log "$BASENAME still starting...there may be a problem"
+  fi
 }
 
 java_stop() {
-  $JAVA_HOME/bin/java $TOMCAT_OPTS $CATALINA_OPTS stop >>$STDLOG 2>&1
+  su_cmd $JAVA_HOME/bin/java $TOMCAT_OPTS $CATALINA_OPTS stop
+#  $JAVA_HOME/bin/java $TOMCAT_OPTS $CATALINA_OPTS stop >>$STDLOG 2>&1
   # Give it a few seconds to stop (to delete PID file)
   PID=`cat ${PIDFILE} 2>/dev/null`
   i=1
@@ -245,7 +314,7 @@ java_stop() {
   if [ -z "$PID" ]; then
     rm -f $PIDFILE
   elif [ "$killsignal" -ne 0 ]; then
-    echo "Killing $BASENAME (kill -$killsignal $PID)"
+    log "Killing $BASENAME (kill -$killsignal $PID)"
     kill -$killsignal $PID
     sleep 1
     PID=`ps -p $PID -o pid | tail -n +2`
@@ -255,6 +324,7 @@ java_stop() {
 
 case "$1" in
   start)
+    create_log
     # Don't try to start up twice!
     if [ -e ${PIDFILE} ]; then
       PID=`cat ${PIDFILE}`
@@ -265,10 +335,9 @@ case "$1" in
     fi
     # jsvc doesn't abort if somebody else is on our port, so let's be smart!
     if [ -n "$PORT" ]; then
-      TMPFILE=/tmp/${BASENAME}.status.$$
-      if $LSOF -i:$PORT -Fp > ${TMPFILE}; then
-        echo "No PID file for ${BASENAME}, but port $PORT already in use by pid `cat ${TMPFILE}`"
-	rm -f ${TMPFILE}
+      RESULT=`$LSOF -i :$PORT | grep LISTEN`
+      if [ -n "$RESULT" ]; then
+        echo "No PID file for ${BASENAME}, but port $PORT already in use"
 	exit 1
       fi
     fi
@@ -277,17 +346,19 @@ case "$1" in
     ${STARTUP}_start
     ;;
   stop)
+    create_log
     create_dirs
     PID=`cat ${PIDFILE} 2>/dev/null`
     log "Stopping ${BASENAME} (${PID})"
     ${STARTUP}_stop
     if [ -e ${PIDFILE} ]; then
-      echo "Unable to stop ${BASENAME} (${PID})"
+      log "Unable to stop ${BASENAME} (${PID}), doing thread-dump"
       kill -QUIT ${PID}
       exit 1
     fi
     ;;
   restart|reload)
+    create_log
     create_dirs
     PID=`cat ${PIDFILE} 2>/dev/null`
     log "Restarting ${BASENAME} (${PID}) in ${CATALINA_HOME}"
@@ -310,6 +381,16 @@ case "$1" in
       echo "${BASENAME} not running"
     fi
     ;;
+  dump)
+    if [ -e ${PIDFILE} ]; then
+      PID=`cat ${PIDFILE}`
+      log "Writing thread-dump for ${BASENAME} (${PID}) into ${STDLOG}"
+      kill -QUIT ${PID}
+      exit 0
+    else
+      log "${BASENAME} not running? (No pidfile: ${PIDFILE})"
+    fi
+    ;;
   report)
     # Spit out a very simple status dump (really used by reportall below)
     # Note: fedora and mckoi will almost always report xxx(unknown)
@@ -326,9 +407,12 @@ case "$1" in
       if [ -n "$PID" ]; then
         PORTS=`$LSOF -p $PID -a -iTCP -Fn -n -P | grep -v '-' | sort | uniq | tr 'n' ' '`
         echo "`echo $PID` unknown($BASENAME) `echo $PORTS`"
-      else
+      elif [ `id -u` -eq 0 ] ; then
         # No PIDFILE and noting listening on our configured PORT
         echo "$BASENAME not running on port $PORT"
+      else
+        # lsof might be unreliable, so we really don't know (TODO: Use netstat)
+	echo "$BASENAME might be running"
       fi
     else
       # No PIDFILE and no configured PORT
@@ -341,7 +425,7 @@ case "$1" in
     done
     ;;
   *)
-    echo "Usage: $0 [-b name] [-f -F] {start|stop|restart|status}"
+    usage $0
     exit 1
 esac
 
